# -----------------------------------------------------------------------------
# Dataset
# -----------------------------------------------------------------------------
# List of the dataset names for training, as present in paths_catalog.py
names: "msmt17"

# Name dir
dataset_dir: "MSMT17"

# Name files dir
files_dir: "additional_files"

# Data dir
data_dir: "data"

# Root directory where datasets should be used (and downloaded if not found)
root_dir: "/home/maksimovaam/ReID-diploma/reid-task/"

# The way to download data
from_dvc: False